### ISSUE TITLE
No such file or directory: 'cd-hit'

### ISSUE THREAD

**Issue by samlipworth** [rehrlich/prokka_database_maker#1]
Hi,

I can't get your script to work, I get the following error when trying to make a TB specific database as follows:

input:
python3 database_maker.py -d mtbc_database -n mtbc -t 83332

error:
Traceback (most recent call last):
  File "database_maker.py", line 107, in <module>
    main()
  File "database_maker.py", line 103, in main
    make_database(gbffs, args.outdir + '/pre_db_files', args.db_dir, args.name)
  File "database_maker.py", line 71, in make_database
    call(cmd.split())
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cd-hit'

**Comment by rehrlich** [comment]
Hi,

I was able to reproduce this error by removing cd-hit from my path.  You might be able to fix this error by adding cd-hit to your path.  

Cd-hit is one of Prokka's dependencies.  My script uses Prokka and two of its dependencies, cd-hit, and makeblastdb.  You can find instructions for installing Prokka here:   https://github.com/tseemann/prokka#installation.  After installation, make sure that prokka-genbank_to_fasta_db, cd-hit, and makeblastdb are on your path.

**Comment by samlipworth** [comment]
thanks very much for your helpful reply - I did actually have it installed, in case anyone else has this problem I fixed it by changing 'cd-hit' to cdhit in the script and it now works great - useful programme, thanks!
